# Generated by Django 3.0.3 on 2020-03-01 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermostatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('temperature', models.FloatField(default=21.0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thermostats.Rule')),
                ('thermostat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thermostats.Thermostat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
