# Generated by Django 3.0.3 on 2020-02-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Thermostat',
        ),
    ]
