# Generated by Django 3.0.3 on 2020-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0002_auto_20200219_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
