# Generated by Django 3.0.3 on 2020-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0003_auto_20200301_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermostatlog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thermostatlog',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
