# Generated by Django 3.0.3 on 2020-02-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0003_auto_20200219_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='is_weekend',
        ),
    ]
