# Generated by Django 3.0.3 on 2020-02-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0004_remove_weekday_is_weekend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='days',
            new_name='weekdays',
        ),
    ]
