# Generated by Django 3.0.3 on 2020-02-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0005_auto_20200220_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='temperature',
            field=models.FloatField(default=21.0),
        ),
    ]
