# Generated by Django 3.0.3 on 2020-03-04 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0005_auto_20200304_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thermostatlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
