# Generated by Django 3.0.3 on 2020-03-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermostats', '0007_auto_20200304_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
